### ISSUE TITLE
Upgrade to Dribbble API v1?

### ISSUE THREAD

**Issue by huphtur** [gngrwzrd/dribbble-screen-saver#1]
Seems the screensaver stopped working due to Dribbble's new API?

https://twitter.com/DribbbleSupport/status/652588203124224000

**Comment by gngrwzrd** [comment]
@huphtur Yes i've been waiting for this to happen. I will put out an update to the screensaver sometime in the next couple weeks.

**Comment by huphtur** [comment]
👍

**Comment by gngrwzrd** [comment]
@huphtur I just updated the screen saver, was quicker than I thought. Download it here: http://gngrwzrd.com/dribbble-screen-saver/ Can you please give this a try and let me know? Thanks!

**Comment by huphtur** [comment]
Works like a charm!
