### ISSUE TITLE
macOS Sierra

### ISSUE THREAD

**Issue by koloz193** [gngrwzrd/dribbble-screen-saver#3]
The screensaver doesn't seem to work with macOS Sierra and just comes up as a black screen. When I tried to reinstall it, I got an error stating "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."

**Comment by CalebAmesbury** [comment]
Actually, I'm running El Capitan and getting the same issue.

**Comment by gngrwzrd** [comment]
@CalebAmesbury @zedkey Thanks for pointing this out. I'll have an update out soon.

**Comment by gngrwzrd** [comment]
@CalebAmesbury @zedkey I just released an updated - this requires dribbble authentication in the screen saver options. Please try it. Download it here http://gngrwzrd.com/dribbble-screen-saver/

**Comment by CalebAmesbury** [comment]
@gngrwzrd it's working great!  Thanks for updating this, I really enjoy it.
